### ISSUE TITLE
is commandQueue still necessary? 

### ISSUE THREAD

**Issue by BenCaunt** [First-Tech-Challenge-Team-20434-NCSSM/2022Offseason#1]
https://github.com/First-Tech-Challenge-Team-20434-NCSSM/2022Offseason/blob/bb796fbe976375d7642610cf6eb5bee132eec32b/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CommandFramework/CommandScheduler.java#L14

My linter detects this as unused code, I am not sure if this is needed for future functionality.

**Comment by jacobvm04** [comment]
It is not, all of the methods that used it were removed due to switching to the other way of scheduling commands, and I forgot to remove that variable too.

**Comment by BenCaunt** [comment]
Okay, I will remove it for the next refactor.
